version: '3'

services:
  database1:
    image: postgres:10
    volumes:
      - database1_volume:/var/lib/postgresql/data
    env_file:
      - config/db/database1_env
    networks:
      - database1_network

  omdbapi:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - .:/opt/omdbapi/src
      - static:/opt/omdbapi/static
      - media:/opt/omdbapi/media
    networks:
      - database1_network
      - nginx_network
    depends_on:
      - database1

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/opt/omdbapi/static
      - media:/opt/omdbapi/media
    networks:
      - nginx_network
    depends_on:
      - omdbapi

networks:
  database1_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  database1_volume:
  static:
  media:
